# Use an empty string if you have multiple domain linking to your website
# This string is used to generate the absolute URL for your assets.
baseURL = 'https://angelicasantana.com/'
defaultContentLanguage = 'es'
ignoreLogs = ['sections-none-/', 'sections-none-/en/']
# Emoji in markdown files
enableEmoji = true
languageCode = 'es-ec'
# Number of blog post per page
paginate = 10
enableRobotsTXT = true
# Title of the website is used for the meta tag title
# and the square icon (not the favicon)
title = 'Angélica Santana Diseño Creativo'

[params]
customCSS = [
	"style/style.css",
	"style/theme.sass",
] # Path relative to assets folder
customJS = ["js/console.js"] # Path relative to assets folder
# Homepage description
# For blog page description you can overwrite it
# in the front matter
description = "Arts and Creative Design inspired by the Galapagos Archipelago"
email = "angysantana551@gmail.com"
favicon = '/favicon.ico'
# Dark mode support
# Supported value are :
# - off
# - always
# If commented the theme will use the browser theme.
# darkMode = 'always'

# Social parameters for contact_icons widget
[[params.social]]
alt = "email icon"
icon = "/icons/email.svg"
name = "email"
url = "mailto:angysantana551@gmail.com"

# [[params.social]]
# alt = "github icon"
# blank = true
# icon = "/icons/github.svg"
# name = "github"
# url = "https://github.com/"
#
# [[params.social]]
# alt = "medium icon"
# blank = true
# icon = "/icons/medium.svg"
# name = "medium"
# url = "https://medium.com/"
#
# [[params.social]]
# alt = "stack-overflow icon"
# blank = true
# icon = "/icons/stack-overflow.svg"
# name = "stack-overflow"
# url = "https://stackoverflow.com/"

[[params.social]]
alt = "Instagram icon"
blank = true
icon = "/icons/instagram.png"
name = "Instagram"
url = "https://instagram.com/angelica_santana_dc"

[[params.social]]
alt = "Instagram icon"
blank = true
icon = "/icons/instagram.png"
name = "Instagram"
url = "https://instagram.com/chocolatitagalapagos"

# Navigation bar
[menu]

[[menu.main]]
identifier = "home" # identifier is use for translations
pre = "" # pre is inserted before the translation (icons, image, etc)
url = "/"
weight = 10

[[menu.main]]
identifier = "blog" # identifier is use for translations
pre = "" # pre is inserted before the translation (icons, image, etc)
url = "/blog/"
weight = 20

[[menu.main]]
identifier = "gallery" # identifier is use for translations
pre = "" # pre is inserted before the translation (icons, image, etc)
url = "/fotos/"
weight = 20

[[menu.main]]
identifier = "contact" # identifier is use for translations
pre = "" # pre is inserted before the translation (icons, image, etc)
url = "/#contact"
weight = 30

# Syntax highlightning
[markup.highlight]
guessSyntax = true
lineNumbersInTable = true
noClasses = false # Set to false to use the Pico default theme.
tabWidth = 2

[taxonomies]
category = "categories"
tag = "tags"

# Translation
# English, French and Italian are supported but you can contribute
# by adding translation to i18n/ folder.
[languages.en]
contentDir = 'content/en'
languageCode = 'en'
languageName = 'English'
weight = 0

# [languages.fr]
# contentDir = 'content/fr'
# languageCode = 'fr'
# languageName = 'Français'
# weight = 2

# Uncomment the following lines to add an italian translation.
# [languages.it]
# contentDir = 'content/it'
# languageCode = 'it'
# languageName = 'Italiano'
# weight = 3

# Uncomment the following lines to add an spanish translation.
[languages.es]
contentDir = 'content/es'
languageCode = 'es'
languageName = 'Español'
weight = 4

[module]
  [[module.imports]]
    path = "github.com/HugoBlox/hugo-blox-builder/modules/blox-tailwind"

  [[module.mounts]]
    source = "content"
    target = "content"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "data"
    target = "data"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "i18n"
    target = "i18n"
  [[module.mounts]]
    source = "archetypes"
    target = "archetypes"
  [[module.mounts]]
    source = "hugo_stats.json"
    target = "assets/hugo_stats.json"
    disableWatch = true
